export { supabase, createRealtimeClient } from './client.js';
export type { Database, Json } from './types/database.js';
export { vectorSearch } from './rpc/vectorSearch.js';
export { graphTraverse } from './rpc/graphTraverse.js';
export { fulltextSearch } from './rpc/fulltextSearch.js';
export { contentVectorSearch } from './rpc/contentSearch.js';
export { newsVectorSearch } from './rpc/newsSearch.js';
export { transcriptVectorSearch } from './rpc/transcriptSearch.js';
export type { VectorSearchResult } from './rpc/vectorSearch.js';
export type { GraphTraverseResult } from './rpc/graphTraverse.js';
export type { FulltextSearchResult } from './rpc/fulltextSearch.js';
export type { ContentVectorSearchResult } from './rpc/contentSearch.js';
export type { NewsVectorSearchResult } from './rpc/newsSearch.js';
export type { TranscriptVectorSearchResult } from './rpc/transcriptSearch.js';
