// This file is auto-generated by Supabase CLI.
// Run: pnpm --filter @platform/db generate-types
// DO NOT EDIT MANUALLY.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      team_members: {
        Row: {
          id: string;
          name: string;
          email: string;
          signal_number: string | null;
          role: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['team_members']['Row'], 'id' | 'created_at' | 'updated_at'> & { id?: string };
        Update: Partial<Database['public']['Tables']['team_members']['Insert']>;
      };
      companies: {
        Row: {
          id: string;
          name: string;
          industry: string | null;
          size: string | null;
          website: string | null;
          linkedin_url: string | null;
          notes: string | null;
          source: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['companies']['Row'], 'id' | 'created_at' | 'updated_at'> & { id?: string };
        Update: Partial<Database['public']['Tables']['companies']['Insert']>;
      };
      contacts: {
        Row: {
          id: string;
          first_name: string;
          last_name: string;
          email: string | null;
          phone: string | null;
          signal_number: string | null;
          company_id: string | null;
          pipeline_stage: string;
          bitcoin_literacy: string;
          owner_id: string | null;
          notes: string | null;
          source: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['contacts']['Row'], 'id' | 'created_at' | 'updated_at'> & { id?: string };
        Update: Partial<Database['public']['Tables']['contacts']['Insert']>;
      };
      interactions: {
        Row: {
          id: string;
          contact_id: string | null;
          company_id: string | null;
          team_member_id: string | null;
          type: string;
          direction: string | null;
          summary: string | null;
          transcript: string | null;
          extracted_data: Json | null;
          duration_seconds: number | null;
          occurred_at: string;
          source: string | null;
          external_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['interactions']['Row'], 'id' | 'created_at' | 'updated_at'> & { id?: string };
        Update: Partial<Database['public']['Tables']['interactions']['Insert']>;
      };
      projects: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          status: string;
          priority: string;
          owner_id: string | null;
          target_date: string | null;
          completed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['projects']['Row'], 'id' | 'created_at' | 'updated_at'> & { id?: string };
        Update: Partial<Database['public']['Tables']['projects']['Insert']>;
      };
      tasks: {
        Row: {
          id: string;
          title: string;
          description: string | null;
          project_id: string | null;
          parent_task_id: string | null;
          status: string;
          priority: string;
          assigned_to: string | null;
          contact_id: string | null;
          due_date: string | null;
          completed_at: string | null;
          source: string | null;
          source_activity_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['tasks']['Row'], 'id' | 'created_at' | 'updated_at'> & { id?: string };
        Update: Partial<Database['public']['Tables']['tasks']['Insert']>;
      };
      content_items: {
        Row: {
          id: string;
          title: string;
          type: string;
          status: string;
          body: string | null;
          scheduled_for: string | null;
          published_at: string | null;
          author_id: string | null;
          knowledge_item_ids: string[] | null;
          iteration_count: number;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['content_items']['Row'], 'id' | 'created_at' | 'updated_at'> & { id?: string };
        Update: Partial<Database['public']['Tables']['content_items']['Insert']>;
      };
      brand_assets: {
        Row: {
          id: string;
          name: string;
          type: string;
          content: string;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['brand_assets']['Row'], 'id' | 'created_at' | 'updated_at'> & { id?: string };
        Update: Partial<Database['public']['Tables']['brand_assets']['Insert']>;
      };
      knowledge_items: {
        Row: {
          id: string;
          title: string;
          url: string | null;
          source_type: string;
          raw_content: string;
          summary: string | null;
          stance: string | null;
          bitcoin_relevance: string | null;
          topic_tags: string[] | null;
          embedding: number[] | null;
          fts: unknown | null;
          published_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['knowledge_items']['Row'], 'id' | 'created_at' | 'updated_at' | 'fts'> & { id?: string };
        Update: Partial<Database['public']['Tables']['knowledge_items']['Insert']>;
      };
      knowledge_connections: {
        Row: {
          id: string;
          source_item_id: string;
          target_item_id: string;
          relationship: string;
          confidence: number | null;
          reasoning: string | null;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['knowledge_connections']['Row'], 'id' | 'created_at'> & { id?: string };
        Update: Partial<Database['public']['Tables']['knowledge_connections']['Insert']>;
      };
      requirements: {
        Row: {
          id: string;
          title: string;
          raw_input: string;
          user_stories: Json | null;
          acceptance_criteria: Json | null;
          assumptions: string[] | null;
          constraints: string[] | null;
          out_of_scope: string[] | null;
          dependencies: Json | null;
          clarification_rounds: Json | null;
          status: string;
          task_id: string | null;
          project_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['requirements']['Row'], 'id' | 'created_at' | 'updated_at'> & { id?: string };
        Update: Partial<Database['public']['Tables']['requirements']['Insert']>;
      };
      risk_register: {
        Row: {
          id: string;
          title: string;
          description: string | null;
          project_id: string | null;
          severity: string;
          likelihood: string;
          status: string;
          mitigation: string | null;
          owner_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['risk_register']['Row'], 'id' | 'created_at' | 'updated_at'> & { id?: string };
        Update: Partial<Database['public']['Tables']['risk_register']['Insert']>;
      };
      reminders: {
        Row: {
          id: string;
          body: string;
          remind_at: string;
          status: string;
          contact_id: string | null;
          task_id: string | null;
          created_by: string | null;
          fired_at: string | null;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['reminders']['Row'], 'id' | 'created_at'> & { id?: string };
        Update: Partial<Database['public']['Tables']['reminders']['Insert']>;
      };
      agent_conversations: {
        Row: {
          id: string;
          thread_id: string;
          agent_name: string;
          participant_signal: string | null;
          messages: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['agent_conversations']['Row'], 'id' | 'created_at' | 'updated_at'> & { id?: string };
        Update: Partial<Database['public']['Tables']['agent_conversations']['Insert']>;
      };
      agent_activity: {
        Row: {
          id: string;
          agent_name: string;
          action: string;
          status: string;
          trigger_type: string | null;
          workflow_run_id: string | null;
          entity_type: string | null;
          entity_id: string | null;
          proposed_actions: Json | null;
          approved_actions: Json | null;
          clarifications: Json | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['agent_activity']['Row'], 'id' | 'created_at' | 'updated_at'> & { id?: string };
        Update: Partial<Database['public']['Tables']['agent_activity']['Insert']>;
      };
      platform_capabilities: {
        Row: {
          id: string;
          agent_name: string;
          capability: string;
          description: string | null;
          status: string;
          phase: string | null;
          tools_required: string[] | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['platform_capabilities']['Row'], 'id' | 'created_at' | 'updated_at'> & { id?: string };
        Update: Partial<Database['public']['Tables']['platform_capabilities']['Insert']>;
      };
      capacity_gaps: {
        Row: {
          id: string;
          gap_type: string;
          description: string;
          directive: string | null;
          agent_name: string | null;
          resolved: boolean;
          resolution_notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['capacity_gaps']['Row'], 'id' | 'created_at' | 'updated_at'> & { id?: string };
        Update: Partial<Database['public']['Tables']['capacity_gaps']['Insert']>;
      };
      forms: {
        Row: {
          id: string;
          name: string;
          slug: string;
          schema: Json;
          active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['forms']['Row'], 'id' | 'created_at' | 'updated_at'> & { id?: string };
        Update: Partial<Database['public']['Tables']['forms']['Insert']>;
      };
      form_submissions: {
        Row: {
          id: string;
          form_id: string;
          data: Json;
          ip_address: string | null;
          contact_id: string | null;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['form_submissions']['Row'], 'id' | 'created_at'> & { id?: string };
        Update: Partial<Database['public']['Tables']['form_submissions']['Insert']>;
      };
    };
    Views: {
      v_open_tasks: {
        Row: Record<string, unknown>;
      };
      v_recent_interactions: {
        Row: Record<string, unknown>;
      };
      v_contacts_overview: {
        Row: Record<string, unknown>;
      };
      v_unresolved_capacity_gaps: {
        Row: Record<string, unknown>;
      };
      v_active_capabilities: {
        Row: Record<string, unknown>;
      };
    };
    Functions: {
      vector_search: {
        Args: { query_embedding: number[]; match_threshold: number; match_count: number };
        Returns: Array<{ id: string; title: string; summary: string | null; similarity: number }>;
      };
      graph_traverse: {
        Args: { start_item_id: string; relationship_filter: string | null; max_depth: number };
        Returns: Array<{ id: string; title: string; relationship: string; depth: number }>;
      };
    };
    Enums: Record<string, never>;
  };
}
